---
- name: Converge
  hosts: all
  become: true

  pre_tasks:
    - name: Update apt cache.
      apt: update_cache=yes cache_valid_time=600
      when: ansible_os_family == 'Debian'
      changed_when: false

  roles:
    - role: tj.netbird
      vars:
        netbird_install_method: 'script'
        netbird_setup_key: ''  # Don't actually connect during testing
        netbird_auto_connect: false
        netbird_check_status: false
